### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by stereobooster** [pmndrs/use-gesture#651]
**Describe the bug**

I got empty page on website and following error in console

```
Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Sandbox or Video**

n/a. Right now reproducible in production https://use-gesture.netlify.app/docs/options/

**Information:**
 - Use Gesture version: n/a
 - Device: Macbook
 - OS: MacOS 14.1.1
 - Browser: firefox

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).
  - [x] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

**PS**

Website worked like 1 week ago. But it have been broken since yesterday. The most interesting here is that, it seems, there were no deployments in 4 months and it broke by itself

**Comment by stereobooster** [comment]
**Upd**. In chrome it shows the same error in console, but content stays

<img width="1202" alt="Screenshot 2024-03-08 at 16 06 18" src="https://github.com/pmndrs/use-gesture/assets/179534/e9b998f1-08fd-4211-a98c-3af09c98e79e">

**Comment by dbismut** [comment]
Content stays in Firefox for me but I still see the error, thanks for the heads up I'll see if I can fix this.

**Comment by dbismut** [comment]
Hydration errors, the best!

**Comment by stereobooster** [comment]
> Hydration errors, the best!

yeah 😬 

Maybe it's version of Firefox? In my case 123.0.1 (64-bit). Because website worked like a week ago

**Comment by jleufven** [comment]
Still dead (or it was working yesterday for me). Running Chrome 122 on a Mac. 

Content is shown briefly, and the it is cleared and errors are logged in the console.

**Comment by dbismut** [comment]
Hey I've manually deployed a fix. There's still some SSR errors that I suspect are due to the smooth-doc package I'm using and that I'm too lazy to update anyway.

**Comment by Awjin** [comment]
Sorry—still broken for me, both Chrome and Safari.

Here's the unminified error: https://react.dev/errors/130?invariant=130&args%5B%5D=undefined&args%5B%5D=

<img width="590" alt="Screenshot 2024-04-11 at 18 59 23" src="https://github.com/pmndrs/use-gesture/assets/3211874/dab3affc-8413-47de-b502-cf7769d23e64">

**Comment by flazouh** [comment]
I got the same on ARC + Chrome

<img width="1166" alt="image" src="https://github.com/pmndrs/use-gesture/assets/25705704/34306f23-b5a8-4b13-bb2c-696e45898c42">

```ts
three.module.js:16815 THREE.WebGLRenderer: Error creating WebGL context.
ll @ three.module.js:16815
Show 1 more frame
Show less
three.module.js:16815 THREE.WebGLRenderer: Error creating WebGL context.
ll @ three.module.js:16815
Show 1 more frame
Show less
three.module.js:16815 THREE.WebGLRenderer: Error creating WebGL context.
ll @ three.module.js:16815
Show 1 more frame
Show less
three.module.js:16815 THREE.WebGLRenderer: Error creating WebGL context.
ll @ three.module.js:16815
Show 1 more frame
Show less
react-dom.production.min.js:189 Error: Error creating WebGL context.
    at new ll (three.module.js:16798:17)
    at ce (index-208291a3.esm.js:1516:69)
    at Object.configure (index-208291a3.esm.js:1575:18)
    at react-three-fiber.esm.js:146:18
    at Eo (react-dom.production.min.js:167:137)
    at Su (react-dom.production.min.js:193:57)
    at Ei (react-dom.production.min.js:294:275)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
du @ react-dom.production.min.js:189
Show 1 more frame
Show less
react-dom.production.min.js:189 Error: Error creating WebGL context.
    at new ll (three.module.js:16798:17)
    at ce (index-208291a3.esm.js:1516:69)
    at Object.configure (index-208291a3.esm.js:1575:18)
    at react-three-fiber.esm.js:146:18
    at Eo (react-dom.production.min.js:167:137)
    at Su (react-dom.production.min.js:193:57)
    at Ei (react-dom.production.min.js:294:275)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
du @ react-dom.production.min.js:189
Show 1 more frame
Show less
react-dom.production.min.js:127 Uncaught Error: Error creating WebGL context.
    at new ll (three.module.js:16798:17)
    at ce (index-208291a3.esm.js:1516:69)
    at Object.configure (index-208291a3.esm.js:1575:18)
    at react-three-fiber.esm.js:146:18
    at Eo (react-dom.production.min.js:167:137)
    at Su (react-dom.production.min.js:193:57)
    at Ei (react-dom.production.min.js:294:275)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
carbon.js?serve=CEAI42QM&placement=use-gesturenetlifyapp:1 Carbon ad connectivity issue! https://srv.carbonads.net/ads/CEAI42QM.json?segment=placement:use-gesturenetlifyapp&viewable=true due to TypeError: Cannot read properties of null (reading 'src')
    at Object.getUrlVar (carbon.js?serve=CEAI42QM&placement=use-gesturenetlifyapp:1:11762)
    at _carbonads_go (carbon.js?serve=CEAI42QM&placement=use-gesturenetlifyapp:1:32922)
    at carbon.js?serve=CEAI42QM&placement=use-gesturenetlifyapp:1:4433
options/:1 Third-party cookie will be blocked. Learn more in the Issues tab.
```
