### ISSUE TITLE
Website not working (use-gesture.netlify.app)

### ISSUE THREAD

**Issue by Profesor08** [pmndrs/use-gesture#679]
**Describe the bug**
> Unable to use website

**Sandbox or Video**
> ![image](https://github.com/user-attachments/assets/e8892256-38bd-4731-980a-b2feabff4799)
> 

https://github.com/user-attachments/assets/1cfb100e-446e-4980-9d68-79873928fc2e

**Information:**
Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fs (react-dom.production.min.js:303:64)
    at e (react-dom.production.min.js:161:400)
    at wu (react-dom.production.min.js:192:323)
    at Ei (react-dom.production.min.js:294:9)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at os (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at jl (react-dom.production.min.js:127:105)

**Comment by dbismut** [comment]
Closing until more details are provided.

**Comment by Profesor08** [comment]
@dbismut  It is bug, and not working. Look at video, no extensions enabled. Localstarage has this peace of code, and this is cause of bug. 
![image](https://github.com/user-attachments/assets/1ce9b5fe-7062-420e-b89b-014e0a3c10d2)

**Comment by dbismut** [comment]
Ok I'll have a look when I can but unfortunately I'm really busy atm.

**Comment by kai-dorschner-twinsity** [comment]
docs are still unavailable.

EDIT: only some links do not work:
![image](https://github.com/user-attachments/assets/b3bc00ba-98a6-4ec9-8c11-18f4163d7153)

**Comment by FLOATING-POINT** [comment]
Same here, all links to docs no longer work - Netlify site cannot be found - use-gesture.netlify.app

**Comment by cmdcolin** [comment]
there is a dead link in the github README on imgur now too

**Comment by Profesor08** [comment]
Currently the original issue is not reproducing. Dead links are not related to.
